/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useContentStash: (typeof import("../composables/useContentStash"))["default"];
  const useFoo: (typeof import("../composables/useFoo"))["default"];
}
