FROM dunglas/frankenphp

RUN install-php-extensions \
    bcmath \
    curl \
    gd \
    json \
    mbstring \
    pcntl \
    pdo_pgsql \
    pgsql \
    redis \
    tokenizer \
    xml \
    zip

COPY . /app

WORKDIR /app/apps/example

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]