/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UiAlert: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/alert/Alert.vue')['default']
    UiAlertDescription: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/alert/AlertDescription.vue')['default']
    UiAlertTitle: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/alert/AlertTitle.vue')['default']
    UiButton: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/button/Button.vue')['default']
    UiDropdownMenu: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    UiDropdownMenuCheckboxItem: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    UiDropdownMenuContent: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    UiDropdownMenuGroup: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    UiDropdownMenuItem: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    UiDropdownMenuLabel: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    UiDropdownMenuRadioGroup: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    UiDropdownMenuRadioItem: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    UiDropdownMenuSeparator: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    UiDropdownMenuShortcut: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    UiDropdownMenuSub: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    UiDropdownMenuSubContent: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    UiDropdownMenuSubTrigger: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    UiDropdownMenuTrigger: typeof import('./../../../../../apps/example/vendor/contentstash/core/resources/ts/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
  }
}
