/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useContentStash: (typeof import("../../../../../apps/example/vendor/contentstash/core/resources/ts/composables/useContentStash"))["default"];
  const useContentStashCore: (typeof import("../../../../../apps/example/vendor/contentstash/core/resources/ts/composables/useContentStashCore"))["default"];
}
