name: Release

on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [20]
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      # See: https://danwakeem.medium.com/beware-the-release-please-v4-github-action-ee71ff9de151
      RELEASE_PREFIX: 'chore(main): release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish core to TODO
        if: ${{ steps.release.outputs['packages/core--release_created'] }}
        run: |
          echo "Publishing core to TODO"